name: 02-workflow-events
on: 
  pull_request:
  workflow_dispatch:
jobs:
   job1:
     runs-on: ubuntu-latest
     steps:
     - run : |
        aws --version
        java --version 
        apt updatte
        apt install apache2 -y
        service apache2 status        