name: 03-workflow
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: Os cmds  
      run: |
          pwd
          ls -l    
      working-directory: test1  
    - name: step3-od cmds
      run: pwd    
      